import clr

clr.AddReference("ZwManaged")
clr.AddReference("ZwDatabaseMgd")

from ZwSoft.ZwCAD.EditorInput import PromptStatus
from System.Collections import ArrayList, Hashtable


def log(msg):
    cad.Msg("[ENTMAKE TEST] " + msg)


def pair(code, value):
    h = Hashtable()
    h["code"] = code
    h["value"] = value
    return h


log("Avvio test EntMake/EntGet/EntMod")

res = cad.GetPoint("Punto base entmake test:")
if res.Status != PromptStatus.OK:
    log("Operazione annullata.")
else:
    p = res.Value

    line_pairs = ArrayList()
    line_pairs.Add(pair(0, "LINE"))
    line_pairs.Add(pair(8, "0"))
    line_pairs.Add(pair(62, 1))
    line_pairs.Add(pair(10, p.X))
    line_pairs.Add(pair(20, p.Y))
    line_pairs.Add(pair(30, p.Z))
    line_pairs.Add(pair(11, p.X + 50.0))
    line_pairs.Add(pair(21, p.Y + 10.0))
    line_pairs.Add(pair(31, p.Z))
    line_id = cad.EntMake(line_pairs)
    log("EntMake LINE ok, handle=" + cad.GetEntityHandle(line_id))

    line_mod = ArrayList()
    line_mod.Add(pair(39, 2.5))
    line_mod.Add(pair(210, 0.0))
    line_mod.Add(pair(220, 0.0))
    line_mod.Add(pair(230, 1.0))
    cad.EntMod(line_id, line_mod)
    line_map = cad.EntGetMap(line_id)
    log("EntGetMap LINE start/end x = " + str(line_map[10]) + "/" + str(line_map[11]))
    log("EntGetMap LINE thickness/normalz = " + str(line_map[39]) + "/" + str(line_map[230]))

    circle_pairs = ArrayList()
    circle_pairs.Add(pair(0, "CIRCLE"))
    circle_pairs.Add(pair(8, "PYLOAD_ENTMAKE"))
    circle_pairs.Add(pair(62, 2))
    circle_pairs.Add(pair(10, p.X + 80.0))
    circle_pairs.Add(pair(20, p.Y))
    circle_pairs.Add(pair(30, p.Z))
    circle_pairs.Add(pair(40, 14.0))
    circle_id = cad.EntMake(circle_pairs)
    log("EntMake CIRCLE ok, handle=" + cad.GetEntityHandle(circle_id))

    entget = cad.EntGet(circle_id)
    log("EntGet count = " + str(len(entget)))
    entmap = cad.EntGetMap(circle_id)
    log("EntGetMap circle dxf = " + str(entmap[0]))
    log("EntGetMap circle layer = " + str(entmap[8]))
    log("EntGetMap circle radius = " + str(entmap[40]))

    mod_pairs = ArrayList()
    mod_pairs.Add(pair(62, 3))
    mod_pairs.Add(pair(8, "PYLOAD_ENTMAKE_MOD"))
    mod_pairs.Add(pair(6, "Continuous"))
    mod_pairs.Add(pair(48, 0.75))
    mod_pairs.Add(pair(60, 0))
    mod_pairs.Add(pair(370, 35))
    mod_pairs.Add(pair(40, 20.0))
    mod_pairs.Add(pair(10, p.X + 90.0))
    mod_pairs.Add(pair(20, p.Y + 5.0))
    mod_pairs.Add(pair(30, p.Z))
    cad.EntMod(circle_id, mod_pairs)
    info = cad.GetCircleInfo(circle_id)
    common = cad.GetEntityCommonInfo(circle_id)
    circle_map = cad.EntGetMap(circle_id)
    log("EntMod CIRCLE -> radius=" + str(info["radius"]) + " color=" + str(info["color_index"]) + " layer=" + str(info["layer"]))
    log("EntMod CIRCLE -> linetype=" + str(common["linetype"]) + " lineweight=" + str(common["lineweight"]))
    log("EntGetMap CIRCLE center/radius = " + str(circle_map[10]) + "/" + str(circle_map[40]))

    arc_pairs = ArrayList()
    arc_pairs.Add(pair(0, "ARC"))
    arc_pairs.Add(pair(8, "PYLOAD_ENTMAKE"))
    arc_pairs.Add(pair(10, p.X + 110.0))
    arc_pairs.Add(pair(20, p.Y + 55.0))
    arc_pairs.Add(pair(30, p.Z))
    arc_pairs.Add(pair(40, 16.0))
    arc_pairs.Add(pair(50, 20.0))
    arc_pairs.Add(pair(51, 140.0))
    arc_id = cad.EntMake(arc_pairs)
    arc_mod = ArrayList()
    arc_mod.Add(pair(39, 1.5))
    arc_mod.Add(pair(210, 0.0))
    arc_mod.Add(pair(220, 0.0))
    arc_mod.Add(pair(230, 1.0))
    arc_mod.Add(pair(50, 25.0))
    arc_mod.Add(pair(51, 160.0))
    cad.EntMod(arc_id, arc_mod)
    arc_map = cad.EntGetMap(arc_id)
    log("EntMake ARC ok, handle=" + cad.GetEntityHandle(arc_id))
    log("EntGetMap ARC center/radius = " + str(arc_map[10]) + "/" + str(arc_map[40]))
    log("EntGetMap ARC angles = " + str(arc_map[50]) + "/" + str(arc_map[51]))

    point_pairs = ArrayList()
    point_pairs.Add(pair(0, "POINT"))
    point_pairs.Add(pair(8, "PYLOAD_ENTMAKE"))
    point_pairs.Add(pair(10, p.X + 140.0))
    point_pairs.Add(pair(20, p.Y + 55.0))
    point_pairs.Add(pair(30, p.Z))
    point_id = cad.EntMake(point_pairs)
    point_mod = ArrayList()
    point_mod.Add(pair(39, 0.75))
    point_mod.Add(pair(210, 0.0))
    point_mod.Add(pair(220, 0.0))
    point_mod.Add(pair(230, 1.0))
    cad.EntMod(point_id, point_mod)
    point_map = cad.EntGetMap(point_id)
    log("EntMake POINT ok, handle=" + cad.GetEntityHandle(point_id))
    log("EntGetMap POINT pos/thickness = " + str(point_map[10]) + "/" + str(point_map[39]))

    poly_pairs = ArrayList()
    poly_pairs.Add(pair(0, "LWPOLYLINE"))
    poly_pairs.Add(pair(8, "PYLOAD_ENTMAKE"))
    poly_pairs.Add(pair(70, 1))
    poly_pairs.Add(pair(10, p.X + 120.0))
    poly_pairs.Add(pair(20, p.Y))
    poly_pairs.Add(pair(10, p.X + 150.0))
    poly_pairs.Add(pair(20, p.Y))
    poly_pairs.Add(pair(10, p.X + 150.0))
    poly_pairs.Add(pair(20, p.Y + 20.0))
    poly_pairs.Add(pair(10, p.X + 120.0))
    poly_pairs.Add(pair(20, p.Y + 20.0))
    poly_id = cad.EntMake(poly_pairs)
    log("EntMake LWPOLYLINE ok, handle=" + cad.GetEntityHandle(poly_id))
    poly_map = cad.EntGetMap(poly_id)
    log("EntGetMap poly vertices = " + str(poly_map[90]))
    log("EntGetMap poly closed = " + str(poly_map[70]))

    poly_mod = ArrayList()
    poly_mod.Add(pair(40, 0.5))
    poly_mod.Add(pair(40, 1.5))
    poly_mod.Add(pair(40, 0.5))
    poly_mod.Add(pair(40, 1.5))
    poly_mod.Add(pair(41, 1.0))
    poly_mod.Add(pair(41, 2.0))
    poly_mod.Add(pair(41, 1.0))
    poly_mod.Add(pair(41, 2.0))
    poly_mod.Add(pair(42, 0.25))
    poly_mod.Add(pair(42, 0.0))
    poly_mod.Add(pair(42, 0.0))
    poly_mod.Add(pair(42, 0.0))
    cad.EntMod(poly_id, poly_mod)
    poly_map2 = cad.EntGetMap(poly_id)
    log("EntMod LWPOLYLINE -> bulge[0] = " + str(poly_map2[42][0]))
    log("EntMod LWPOLYLINE -> start/end width[0] = " + str(poly_map2[40][0]) + "/" + str(poly_map2[41][0]))

    poly_const_pairs = ArrayList()
    poly_const_pairs.Add(pair(0, "LWPOLYLINE"))
    poly_const_pairs.Add(pair(8, "PYLOAD_ENTMAKE"))
    poly_const_pairs.Add(pair(70, 0))
    poly_const_pairs.Add(pair(43, 1.25))
    poly_const_pairs.Add(pair(10, p.X + 120.0))
    poly_const_pairs.Add(pair(20, p.Y + 35.0))
    poly_const_pairs.Add(pair(10, p.X + 150.0))
    poly_const_pairs.Add(pair(20, p.Y + 35.0))
    poly_const_pairs.Add(pair(10, p.X + 150.0))
    poly_const_pairs.Add(pair(20, p.Y + 50.0))
    poly_const_id = cad.EntMake(poly_const_pairs)
    poly_const_map = cad.EntGetMap(poly_const_id)
    log("EntMake LWPOLYLINE constant width ok, handle=" + cad.GetEntityHandle(poly_const_id))
    log("EntGetMap poly constant width = " + str(poly_const_map[43]))

    text_pairs = ArrayList()
    text_pairs.Add(pair(0, "TEXT"))
    text_pairs.Add(pair(8, "PYLOAD_ENTMAKE"))
    text_pairs.Add(pair(10, p.X + 40.0))
    text_pairs.Add(pair(20, p.Y + 35.0))
    text_pairs.Add(pair(30, p.Z))
    text_pairs.Add(pair(1, "ENTMAKE"))
    text_pairs.Add(pair(40, 4.0))
    text_pairs.Add(pair(50, 15.0))
    text_id = cad.EntMake(text_pairs)
    log("EntMake TEXT ok, handle=" + cad.GetEntityHandle(text_id))

    text_mod = ArrayList()
    text_mod.Add(pair(1, "ENTMOD"))
    text_mod.Add(pair(40, 5.5))
    text_mod.Add(pair(41, 0.85))
    text_mod.Add(pair(71, 2))
    text_mod.Add(pair(51, 10.0))
    text_mod.Add(pair(50, 0.0))
    cad.EntMod(text_id, text_mod)
    text_map = cad.EntGetMap(text_id)
    text_info = cad.GetEntityInfo(text_id)
    log("EntMod TEXT -> type=" + str(text_info["type"]) + " layer=" + str(text_info["layer"]))
    log("EntGetMap TEXT width/oblique = " + str(text_map[41]) + "/" + str(text_map[51]))
    if 71 in text_map:
        log("EntGetMap TEXT genflags = " + str(text_map[71]))
    if 330 in text_map:
        log("EntGetMap TEXT owner handle = " + str(text_map[330]))
    if 67 in text_map:
        log("EntGetMap TEXT paperspace = " + str(text_map[67]))
    if 410 in text_map:
        log("EntGetMap TEXT layout = " + str(text_map[410]))

    mtext_pairs = ArrayList()
    mtext_pairs.Add(pair(0, "MTEXT"))
    mtext_pairs.Add(pair(8, "PYLOAD_ENTMAKE"))
    mtext_pairs.Add(pair(10, p.X + 70.0))
    mtext_pairs.Add(pair(20, p.Y + 35.0))
    mtext_pairs.Add(pair(30, p.Z))
    mtext_pairs.Add(pair(1, "MTEXT ENTMAKE"))
    mtext_pairs.Add(pair(40, 3.5))
    mtext_pairs.Add(pair(41, 25.0))
    mtext_id = cad.EntMake(mtext_pairs)
    log("EntMake MTEXT ok, handle=" + cad.GetEntityHandle(mtext_id))

    mtext_mod = ArrayList()
    mtext_mod.Add(pair(1, "MTEXT ENTMOD"))
    mtext_mod.Add(pair(41, 32.0))
    mtext_mod.Add(pair(71, 1))
    mtext_mod.Add(pair(72, 5))
    mtext_mod.Add(pair(73, 2))
    mtext_mod.Add(pair(44, 1.2))
    cad.EntMod(mtext_id, mtext_mod)
    mtext_map = cad.EntGetMap(mtext_id)
    log("EntGetMap mtext width = " + str(mtext_map[41]))
    if 71 in mtext_map:
        log("EntGetMap mtext attachment = " + str(mtext_map[71]))
    if 72 in mtext_map:
        log("EntGetMap mtext flowdir = " + str(mtext_map[72]))
    if 73 in mtext_map:
        log("EntGetMap mtext linespacingstyle = " + str(mtext_map[73]))
    if 44 in mtext_map:
        log("EntGetMap mtext linespacingfactor = " + str(mtext_map[44]))

    ellipse_pairs = ArrayList()
    ellipse_pairs.Add(pair(0, "ELLIPSE"))
    ellipse_pairs.Add(pair(8, "PYLOAD_ENTMAKE"))
    ellipse_pairs.Add(pair(10, p.X + 190.0))
    ellipse_pairs.Add(pair(20, p.Y + 10.0))
    ellipse_pairs.Add(pair(30, p.Z))
    ellipse_pairs.Add(pair(11, 25.0))
    ellipse_pairs.Add(pair(21, 0.0))
    ellipse_pairs.Add(pair(31, 0.0))
    ellipse_pairs.Add(pair(40, 0.45))
    ellipse_id = cad.EntMake(ellipse_pairs)
    log("EntMake ELLIPSE ok, handle=" + cad.GetEntityHandle(ellipse_id))

    ellipse_mod = ArrayList()
    ellipse_mod.Add(pair(40, 0.60))
    cad.EntMod(ellipse_id, ellipse_mod)
    ellipse_map = cad.EntGetMap(ellipse_id)
    log("EntGetMap ellipse ratio = " + str(ellipse_map[40]))

    ray_pairs = ArrayList()
    ray_pairs.Add(pair(0, "RAY"))
    ray_pairs.Add(pair(8, "PYLOAD_ENTMAKE"))
    ray_pairs.Add(pair(10, p.X + 230.0))
    ray_pairs.Add(pair(20, p.Y))
    ray_pairs.Add(pair(30, p.Z))
    ray_pairs.Add(pair(11, 1.0))
    ray_pairs.Add(pair(21, 0.4))
    ray_pairs.Add(pair(31, 0.0))
    ray_id = cad.EntMake(ray_pairs)
    ray_map = cad.EntGetMap(ray_id)
    log("EntMake RAY ok, handle=" + cad.GetEntityHandle(ray_id))
    log("EntGetMap ray dir x = " + str(ray_map[11]))

    trace_pairs = ArrayList()
    trace_pairs.Add(pair(0, "TRACE"))
    trace_pairs.Add(pair(8, "PYLOAD_ENTMAKE"))
    trace_pairs.Add(pair(10, p.X + 260.0))
    trace_pairs.Add(pair(20, p.Y))
    trace_pairs.Add(pair(30, p.Z))
    trace_pairs.Add(pair(11, p.X + 280.0))
    trace_pairs.Add(pair(21, p.Y))
    trace_pairs.Add(pair(31, p.Z))
    trace_pairs.Add(pair(12, p.X + 275.0))
    trace_pairs.Add(pair(22, p.Y + 15.0))
    trace_pairs.Add(pair(32, p.Z))
    trace_pairs.Add(pair(13, p.X + 255.0))
    trace_pairs.Add(pair(23, p.Y + 15.0))
    trace_pairs.Add(pair(33, p.Z))
    trace_id = cad.EntMake(trace_pairs)
    trace_map = cad.EntGetMap(trace_id)
    log("EntMake TRACE ok, handle=" + cad.GetEntityHandle(trace_id))
    log("EntGetMap trace p4 x = " + str(trace_map[13]))

    face_pairs = ArrayList()
    face_pairs.Add(pair(0, "3DFACE"))
    face_pairs.Add(pair(8, "PYLOAD_ENTMAKE"))
    face_pairs.Add(pair(10, p.X + 275.0))
    face_pairs.Add(pair(20, p.Y + 22.0))
    face_pairs.Add(pair(30, p.Z))
    face_pairs.Add(pair(11, p.X + 295.0))
    face_pairs.Add(pair(21, p.Y + 22.0))
    face_pairs.Add(pair(31, p.Z + 5.0))
    face_pairs.Add(pair(12, p.X + 300.0))
    face_pairs.Add(pair(22, p.Y + 38.0))
    face_pairs.Add(pair(32, p.Z + 10.0))
    face_pairs.Add(pair(13, p.X + 280.0))
    face_pairs.Add(pair(23, p.Y + 40.0))
    face_pairs.Add(pair(33, p.Z + 3.0))
    face_id = cad.EntMake(face_pairs)
    face_map = cad.EntGetMap(face_id)
    log("EntMake 3DFACE ok, handle=" + cad.GetEntityHandle(face_id))
    log("EntGetMap 3DFACE p4 x = " + str(face_map[13]))

    solid_pairs = ArrayList()
    solid_pairs.Add(pair(0, "SOLID"))
    solid_pairs.Add(pair(8, "PYLOAD_ENTMAKE"))
    solid_pairs.Add(pair(10, p.X + 290.0))
    solid_pairs.Add(pair(20, p.Y))
    solid_pairs.Add(pair(30, p.Z))
    solid_pairs.Add(pair(11, p.X + 310.0))
    solid_pairs.Add(pair(21, p.Y))
    solid_pairs.Add(pair(31, p.Z))
    solid_pairs.Add(pair(12, p.X + 305.0))
    solid_pairs.Add(pair(22, p.Y + 15.0))
    solid_pairs.Add(pair(32, p.Z))
    solid_pairs.Add(pair(13, p.X + 285.0))
    solid_pairs.Add(pair(23, p.Y + 15.0))
    solid_pairs.Add(pair(33, p.Z))
    solid_id = cad.EntMake(solid_pairs)
    solid_map = cad.EntGetMap(solid_id)
    log("EntMake SOLID ok, handle=" + cad.GetEntityHandle(solid_id))
    log("EntGetMap solid p4 x = " + str(solid_map[13]))

    leader_pairs = ArrayList()
    leader_pairs.Add(pair(0, "LEADER"))
    leader_pairs.Add(pair(8, "PYLOAD_ENTMAKE"))
    leader_pairs.Add(pair(71, 1))
    leader_pairs.Add(pair(340, mtext_id))
    leader_pairs.Add(pair(10, p.X + 340.0))
    leader_pairs.Add(pair(20, p.Y))
    leader_pairs.Add(pair(30, p.Z))
    leader_pairs.Add(pair(10, p.X + 355.0))
    leader_pairs.Add(pair(20, p.Y + 12.0))
    leader_pairs.Add(pair(30, p.Z))
    leader_pairs.Add(pair(10, p.X + 375.0))
    leader_pairs.Add(pair(20, p.Y + 26.0))
    leader_pairs.Add(pair(30, p.Z))
    leader_id = cad.EntMake(leader_pairs)
    leader_map = cad.EntGetMap(leader_id)
    log("EntMake LEADER ok, handle=" + cad.GetEntityHandle(leader_id))
    log("EntGetMap leader vertex_count = " + str(leader_map[76]))
    log("EntGetMap leader has_arrow = " + str(leader_map[71]))

    leader_mod = ArrayList()
    leader_mod.Add(pair(71, 0))
    cad.EntMod(leader_id, leader_mod)
    leader_map2 = cad.EntGetMap(leader_id)
    log("EntMod LEADER -> has_arrow = " + str(leader_map2[71]))

    owner_info = cad.EntOwnerInfo(text_id)
    log("EntOwnerInfo(TEXT) owner_type = " + str(owner_info["owner_type"]))
    anc = cad.EntAncestors(text_id)
    log("EntAncestors(TEXT) count = " + str(len(anc)))
    sel_model = cad.GetSelectionByDxf([pair(67, 0), pair(410, "Model"), pair(5, cad.GetEntityHandle(text_id))])
    log("GetSelectionByDxf handle+layout+space -> " + str(len(sel_model)))
    sel_circle_center = cad.GetSelectionByDxf([pair(0, "CIRCLE"), pair(10, p.X + 90.0), pair(20, p.Y + 5.0), pair(40, 20.0)])
    log("GetSelectionByDxf CIRCLE center+radius -> " + str(len(sel_circle_center)))
    sel_arc_angles = cad.GetSelectionByDxf([pair(0, "ARC"), pair(50, 25.0), pair(51, 160.0), pair(230, 1.0)])
    log("GetSelectionByDxf ARC angles+normal -> " + str(len(sel_arc_angles)))
    sel_line_coords = cad.GetSelectionByDxf([pair(0, "LINE"), pair(11, p.X + 50.0), pair(21, p.Y + 10.0), pair(39, 2.5)])
    log("GetSelectionByDxf LINE end+thickness -> " + str(len(sel_line_coords)))
    sel_point_pos = cad.GetSelectionByDxf([pair(0, "POINT"), pair(10, p.X + 140.0), pair(20, p.Y + 55.0), pair(230, 1.0)])
    log("GetSelectionByDxf POINT pos+normal -> " + str(len(sel_point_pos)))
    if len(sel_circle_center) == 0:
        dbg = cad.DebugDxfFilterMatch(circle_id, [pair(0, "CIRCLE"), pair(10, p.X + 90.0), pair(20, p.Y + 5.0), pair(40, 20.0)])
        det = dbg["details"]
        log("DEBUG CIRCLE overall matched = " + str(dbg["matched"]))
        log("DEBUG CIRCLE 0 expected/actual/matched = " + str(det[0]["expected"]) + "/" + str(det[0]["actual"]) + "/" + str(det[0]["matched"]))
        log("DEBUG CIRCLE 10 expected/actual = " + str(det[10]["expected"]) + "/" + str(det[10]["actual"]))
        log("DEBUG CIRCLE 20 expected/actual = " + str(det[20]["expected"]) + "/" + str(det[20]["actual"]))
        log("DEBUG CIRCLE 40 expected/actual/matched = " + str(det[40]["expected"]) + "/" + str(det[40]["actual"]) + "/" + str(det[40]["matched"]))
    if len(sel_arc_angles) == 0:
        dbg = cad.DebugDxfFilterMatch(arc_id, [pair(0, "ARC"), pair(50, 25.0), pair(51, 160.0), pair(230, 1.0)])
        det = dbg["details"]
        log("DEBUG ARC overall matched = " + str(dbg["matched"]))
        log("DEBUG ARC 0 expected/actual/matched = " + str(det[0]["expected"]) + "/" + str(det[0]["actual"]) + "/" + str(det[0]["matched"]))
        log("DEBUG ARC 50 expected/actual/matched = " + str(det[50]["expected"]) + "/" + str(det[50]["actual"]) + "/" + str(det[50]["matched"]))
        log("DEBUG ARC 51 expected/actual/matched = " + str(det[51]["expected"]) + "/" + str(det[51]["actual"]) + "/" + str(det[51]["matched"]))
        log("DEBUG ARC 230 expected/actual/matched = " + str(det[230]["expected"]) + "/" + str(det[230]["actual"]) + "/" + str(det[230]["matched"]))
    if len(sel_line_coords) == 0:
        dbg = cad.DebugDxfFilterMatch(line_id, [pair(0, "LINE"), pair(11, p.X + 50.0), pair(21, p.Y + 10.0), pair(39, 2.5)])
        det = dbg["details"]
        log("DEBUG LINE overall matched = " + str(dbg["matched"]))
        log("DEBUG LINE 0 expected/actual/matched = " + str(det[0]["expected"]) + "/" + str(det[0]["actual"]) + "/" + str(det[0]["matched"]))
        log("DEBUG LINE 11 expected/actual/matched = " + str(det[11]["expected"]) + "/" + str(det[11]["actual"]) + "/" + str(det[11]["matched"]))
        log("DEBUG LINE 21 expected/actual/matched = " + str(det[21]["expected"]) + "/" + str(det[21]["actual"]) + "/" + str(det[21]["matched"]))
        log("DEBUG LINE 39 expected/actual/matched = " + str(det[39]["expected"]) + "/" + str(det[39]["actual"]) + "/" + str(det[39]["matched"]))
    if len(sel_point_pos) == 0:
        dbg = cad.DebugDxfFilterMatch(point_id, [pair(0, "POINT"), pair(10, p.X + 140.0), pair(20, p.Y + 55.0), pair(230, 1.0)])
        det = dbg["details"]
        log("DEBUG POINT overall matched = " + str(dbg["matched"]))
        log("DEBUG POINT 0 expected/actual/matched = " + str(det[0]["expected"]) + "/" + str(det[0]["actual"]) + "/" + str(det[0]["matched"]))
        log("DEBUG POINT 10 expected/actual/matched = " + str(det[10]["expected"]) + "/" + str(det[10]["actual"]) + "/" + str(det[10]["matched"]))
        log("DEBUG POINT 20 expected/actual/matched = " + str(det[20]["expected"]) + "/" + str(det[20]["actual"]) + "/" + str(det[20]["matched"]))
        log("DEBUG POINT 230 expected/actual/matched = " + str(det[230]["expected"]) + "/" + str(det[230]["actual"]) + "/" + str(det[230]["matched"]))

    names = cad.GetBlockNames()
    rich_block = None
    for name in names:
        defs = cad.GetBlockAttributeDefinitions(str(name))
        if len(defs) > 0:
            rich_block = str(name)
            break

    if rich_block is not None:
        insert_id = cad.InsertBlock(rich_block, p.X + 420.0, p.Y, p.Z)
        insert_map = cad.EntGetMap(insert_id)
        log("InsertBlock rich ok, handle=" + cad.GetEntityHandle(insert_id))
        log("EntGetMap INSERT has_attrs = " + str(insert_map[66]))

        def_ids = cad.GetBlockDefinitionEntityIds(insert_id)
        log("GetBlockDefinitionEntityIds -> " + str(len(def_ids)))

        attr_ids = cad.GetBlockAttributeReferenceIds(insert_id)
        log("Insert rich AttributeReference count = " + str(len(attr_ids)))
        traversal_info = cad.GetInsertAttributeTraversalInfo(insert_id)
        log("Insert traversal refs/defs/const = " + str(traversal_info["attribute_reference_count"]) + "/" + str(traversal_info["attribute_definition_count"]) + "/" + str(traversal_info["constant_attribute_definition_count"]))
        if len(attr_ids) > 0:
            attr_id = attr_ids[0]
            attr_mod = ArrayList()
            attr_mod.Add(pair(1, "ATTR_RICH"))
            attr_mod.Add(pair(7, "Standard"))
            attr_mod.Add(pair(41, 0.9))
            attr_mod.Add(pair(71, 2))
            attr_mod.Add(pair(51, 12.0))
            attr_mod.Add(pair(70, 1))
            cad.EntMod(attr_id, attr_mod)
            attr_map = cad.EntGetMap(attr_id)
            log("EntMod ATTRIB -> text = " + str(attr_map[1]))
            log("EntGetMap ATTRIB style = " + str(attr_map[7]))
            log("EntGetMap ATTRIB width/oblique = " + str(attr_map[41]) + "/" + str(attr_map[51]))
            log("EntGetMap ATTRIB invisible = " + str(attr_map[70]))
            if 71 in attr_map:
                log("EntGetMap ATTRIB genflags = " + str(attr_map[71]))
            attr_owner_br = cad.EntOwningBlockReference(attr_id)
            log("EntOwningBlockReference(ATTRIB) == insert ? " + str(attr_owner_br == insert_id))
            attr_chain = cad.EntOwnerChainInfo(attr_id)
            log("EntOwnerChainInfo(ATTRIB) count = " + str(len(attr_chain)))
            attr_siblings = cad.EntAttributeSiblings(attr_id)
            log("EntAttributeSiblings(ATTRIB) = " + str(len(attr_siblings)))
            log("EntNextAttribute is null? " + str(cad.EntNextAttribute(attr_id).IsNull))
            log("EntPreviousAttribute is null? " + str(cad.EntPreviousAttribute(attr_id).IsNull))

    hatch_pairs = ArrayList()
    hatch_pairs.Add(pair(0, "HATCH"))
    hatch_pairs.Add(pair(8, "PYLOAD_ENTMAKE"))
    hatch_pairs.Add(pair(2, "SOLID"))
    hatch_pairs.Add(pair(70, 1))
    hatch_pairs.Add(pair(75, 0))
    hatch_pairs.Add(pair(76, 1))
    hatch_pairs.Add(pair(77, 0))
    hatch_pairs.Add(pair(41, 1.0))
    hatch_pairs.Add(pair(52, 15.0))
    hatch_pairs.Add(pair(10, p.X + 470.0))
    hatch_pairs.Add(pair(20, p.Y))
    hatch_pairs.Add(pair(10, p.X + 490.0))
    hatch_pairs.Add(pair(20, p.Y))
    hatch_pairs.Add(pair(10, p.X + 490.0))
    hatch_pairs.Add(pair(20, p.Y + 18.0))
    hatch_pairs.Add(pair(10, p.X + 470.0))
    hatch_pairs.Add(pair(20, p.Y + 18.0))
    hatch_id = cad.EntMake(hatch_pairs)
    hatch_map = cad.EntGetMap(hatch_id)
    log("EntMake HATCH fine ok, handle=" + cad.GetEntityHandle(hatch_id))
    log("EntGetMap HATCH assoc/type = " + str(hatch_map[70]) + "/" + str(hatch_map[76]))
    if 75 in hatch_map:
        log("EntGetMap HATCH style = " + str(hatch_map[75]))
    if 77 in hatch_map:
        log("EntGetMap HATCH double = " + str(hatch_map[77]))
    else:
        log("Nessun blocco con attributi trovato per test INSERT/ATTRIB ricchi")

    last_id = cad.EntLast()
    log("EntLast -> handle=" + cad.GetEntityHandle(last_id))

    copy_id = cad.EntCopy(ellipse_id, 0.0, 25.0, 0.0)
    log("EntCopy ELLIPSE ok, handle=" + cad.GetEntityHandle(copy_id))

    cad.Regen()
    cad.ZoomExtents()
    log("Test EntMake/EntGet/EntMod completato")
